# Escreva um algoritimo que leia um número inteiro qualquer e mostre na tela a sua tabuada
num = int(input('Qual o número a ser calculado na tabuada:_ '))
print('Tabuada de {}:'.format(num))
print('-' * 12)
print('{} x {:2} = {}'.format(num, 1, 1 * num))
print('{} x {:2} = {}'.format(num, 2, 2 * num))
print('{} x {:2} = {}'.format(num, 3, 3 * num))
print('{} x {:2} = {}'.format(num, 4, 4 * num))
print('{} x {:2} = {}'.format(num, 5, 5 * num))
print('{} x {:2} = {}'.format(num, 6, 6 * num))
print('{} x {:2} = {}'.format(num, 7, 7 * num))
print('{} x {:2} = {}'.format(num, 8, 8 * num))
print('{} x {:2} = {}'.format(num, 9, 9 * num))
print('{} x {:2} = {}'.format(num, 10, 10 * num))
print('-' * 12)
